title: <Michelle Gregoire>  # your name (or website title) here
logo: "/images/github_headshot.jpg?raw=true"> #your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   bio: PhD Student in Cell and Molecular Biology at the Univeristy of Rhode Island 
  <br><br>
  <a href="https://www.linkedin.com/in/michelle-gregoire-2017/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

